### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'Conv2d' object has no attribute 'register_full_backward_pre_hook'

### ISSUE THREAD

**Issue by ld-xy** [kshitij12345/torchnnprofiler#6]
torch.nn.modules.module.ModuleAttributeError: 'Conv2d' object has no attribute 'register_full_backward_pre_hook'

Can you help me? thinks

**Comment by kshitij12345** [comment]
Thanks for using the lib and opening the issue.

It seems like your are using older version of PyTorch. Unfortunately for now, we only support nightly version of PyTorch as `full_backward_pre_hook` functionality didn't make it to the 1.13 release.

One thing I am planning to do is to support earlier versions with a warning that we won't be able to track the backward times.
