### ISSUE TITLE
Model with Identity layers

### ISSUE THREAD

**Issue by JacopoMangiavacchi** [kshitij12345/torchnnprofiler#8]
Hi there, thank you for sharing this code.  It's really cool. Anyway, I tried to use it on a model that use some Identity layers and it raise this error when it's trying to append the hook handle for this layer:

AttributeError: 'Identity' object has no attribute 'register_full_backward_pre_hook'

I would say you should probably skip Identity layers.

**Comment by kshitij12345** [comment]
Thanks for giving this a shot @JacopoMangiavacchi 

Looking at the error, I believe that you are not using the nightlies but one of the stable version. Can you please confirm this?

Unfortunately, `register_full_backward_pre_hook` is only available in nightlies :(

Following code works for me
```python
import torch
from nnprofiler import LayerProf, get_children


class MyNet(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv2d = torch.nn.Conv2d(64, 64, 3)
        self.identity = torch.nn.Identity()

    def forward(self, x):
        return self.identity(self.conv2d(x))


net = MyNet().to('cuda:1')
input = torch.randn(16, 64, 224, 224, device='cuda:1')
# Warm-up
net(input).sum().backward()

with LayerProf(net) as prof:
    net(input).sum().backward()

    print(prof.layerwise_summary())

```

Output
```
MyNet(
  (conv2d): Conv2d(Forward Time: 0.183278ms | Backward Time: 0.002610ms)
  (identity): Identity(Forward Time: 0.019509ms | Backward Time: 0.017970ms)
)
```

**Comment by JacopoMangiavacchi** [comment]
Oh sorry, you're totally right.  It's clearly advised in the readme to use nightly builds.  It works with that tanks.  Appreciated.
